name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.4', '8.0', '8.1']
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php-versions }}
